version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/metro_market
      - REDIS_URL=redis://redis:6379
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metro_market
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/scheduler/crontab:/etc/cron.d/symfony
      - ./var/log:/var/www/var/log
    depends_on:
      - php
      - db
      - redis

volumes:
  mysql_data:
  redis_data: